apiVersion: external-secrets.io/v1beta1
kind: ClusterSecretStore
metadata:
  name: secretstore-aws
spec:
  provider:
    aws:
      service: SecretsManager
      # Argo CD의 LoadBalancer 주소를 통해 ap-northeast-2 리전으로 확인했습니다.
      region: ap-northeast-2
      auth:
        # EKS의 IRSA(IAM Roles for Service Accounts) 설정을 사용합니다.
        # external-secrets 컨트롤러가 사용하는 서비스 어카운트를 지정합니다.
        jwt:
          serviceAccountRef:
            name: external-secrets
            namespace: external-secrets 