name: Forwarding Assist CI/CD

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    strategy:
      matrix:
        service:
          - name: document-generator-service
            ecr_repo: document-generator
          - name: regulation-service
            ecr_repo: regulation-service
          - name: error-check-service
            ecr_repo: error-check-service
          - name: regulation-frontend
            ecr_repo: regulation-frontend
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}
      image_tag: ${{ github.sha }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        working-directory: ./${{ matrix.service.name }}
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.service.ecr_repo }}
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG .
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ecr

    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: sususu25/forwarding-assist-k8s-manifests
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}

      - name: Update image tags in manifest
        run: |
          REGISTRY=${{ needs.build-and-push-to-ecr.outputs.registry }}
          IMAGE_TAG=${{ needs.build-and-push-to-ecr.outputs.image_tag }}
          
          sed -i "s|image: .*/document-generator:.*|image: ${REGISTRY}/document-generator:${IMAGE_TAG}|" document-generator-service/deployment.yaml
          sed -i "s|image: .*/regulation-service:.*|image: ${REGISTRY}/regulation-service:${IMAGE_TAG}|" regulation-service/deployment.yaml
          sed -i "s|image: .*/error-check-service:.*|image: ${REGISTRY}/error-check-service:${IMAGE_TAG}|" error-check-service/deployment.yaml
          sed -i "s|image: .*/regulation-frontend:.*|image: ${REGISTRY}/regulation-frontend:${IMAGE_TAG}|" regulation-frontend/deployment.yaml
      
      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          if git diff-index --quiet HEAD; then
            echo "No changes to commit."
          else
            git commit -m "Update image tags to ${{ needs.build-and-push-to-ecr.outputs.image_tag }}"
            git push
          fi 