name: Forwarding Assist CI/CD

on:
  push:
    branches: [ main ] # main 브랜치에 코드가 푸시될 때 실행됩니다.
  workflow_dispatch: # 수동으로 실행할 수도 있게 합니다.

jobs:
  build-and-push-to-ecr:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    
    strategy:
      matrix:
        service: [document-generator-service, regulation-service, error-check-service, regulation-frontend]
    outputs:
      registry: ${{ steps.login-ecr.outputs.registry }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-2

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: ${{ matrix.service }} # matrix에서 서비스 이름을 가져옵니다.
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG ./${{ matrix.service }}
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG 

  update-manifest:
    runs-on: ubuntu-latest
    needs: build-and-push-to-ecr

    steps:
      - name: Checkout manifest repository
        uses: actions/checkout@v3
        with:
          repository: sususu25/forwarding-assist-k8s-manifests
          token: ${{ secrets.MANIFEST_REPO_TOKEN }}

      - name: Update image tags
        run: |
          # 각 서비스의 deployment.yaml 파일을 찾아 이미지 태그를 업데이트합니다.
          # 이 부분은 더 정교한 방법(예: kustomize, yq)으로 개선할 수 있습니다.
          sed -i 's|image: .*/document-generator-service:.*|image: ${{ needs.build-and-push-to-ecr.outputs.registry }}/document-generator-service:${{ github.sha }}|' document-generator-service/deployment.yaml
          sed -i 's|image: .*/regulation-service:.*|image: ${{ needs.build-and-push-to-ecr.outputs.registry }}/regulation-service:${{ github.sha }}|' regulation-service/deployment.yaml
          sed -i 's|image: .*/error-check-service:.*|image: ${{ needs.build-and-push-to-ecr.outputs.registry }}/error-check-service:${{ github.sha }}|' error-check-service/deployment.yaml
          sed -i 's|image: .*/regulation-frontend:.*|image: ${{ needs.build-and-push-to-ecr.outputs.registry }}/regulation-frontend:${{ github.sha }}|' regulation-frontend/deployment.yaml

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git commit -m "Update image tags to ${{ github.sha }}" || echo "No changes to commit"
          git push 